# Generated by Django 6.0 on 2026-01-20 19:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('nickname', config='simple'), name='nicname_User_vector_idx'),
        ),
    ]
