# Generated by Django 4.2.7 on 2025-02-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sunset_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
