# Generated by Django 4.2.20 on 2025-05-22 15:27

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_image'),
    ]

    operations = [HStoreExtension(),
    ]
