# Generated by Django 4.2.20 on 2025-05-22 16:49

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20250522_1827'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(models.F('first_name'), models.F('last_name'), fastupdate=False, name='user_first_last_gin_idx'),
        ),
    ]
