# Generated by Django 5.2 on 2025-06-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20250522_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sunset_time',
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
