# Generated by Django 4.2.20 on 2025-05-22 17:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_user_user_first_last_gin_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_first_last_gin_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('first_name', 'last_name'), name='user_first_last_gin_idx'),
        ),
    ]
