# Generated by Django 6.0 on 2026-01-19 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Отправлено'), ('accepted', 'Принято'), ('rejected', 'Отказано')], db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='friends',
            index=models.Index(fields=['sender', 'receiver'], name='idx_friends_sender_receiver'),
        ),
    ]
