# Generated by Django 4.2.20 on 2025-04-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_alter_friends_receiver_alter_friends_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='application_status',
            field=models.CharField(max_length=15),
        ),
    ]
