# Generated by Django 4.2.20 on 2025-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_alter_friends_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Отправлено'), ('accepted', 'Принято'), ('rejected', 'Отказано')], max_length=15),
        ),
        migrations.AlterModelTable(
            name='friends',
            table='friends',
        ),
    ]
