# Generated by Django 5.2 on 2025-10-18 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_publication', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publications',
            name='topic',
            field=models.TextField(default='Без темы'),
            preserve_default=False,
        ),
    ]
