# Generated by Django 5.2 on 2025-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publications_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publications',
            name='video',
        ),
        migrations.AddField(
            model_name='publications',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='publications_media'),
        ),
    ]
