# Generated by Django 5.2 on 2025-07-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_publications_image_remove_publications_video_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publications',
            table='publications',
        ),
    ]
