# Generated by Django 5.2 on 2025-07-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_publications_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
