# Generated by Django 6.0 on 2026-01-12 21:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_alter_comments_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publications',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('text', 'topic', config='english'), name='topic_publication_vector_idx'),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
