# Generated by Django 6.0 on 2026-01-19 20:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publications_topic_publication_vector_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publications',
            name='topic_publication_vector_idx',
        ),
        migrations.AlterField(
            model_name='publications',
            name='topic',
            field=models.TextField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='publications',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('text', 'topic', config='simple'), name='topic_publication_vector_idx'),
        ),
    ]
