# Generated by Django 6.0 on 2026-01-19 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['sender', 'recipient'], name='idx_friends_sender_recipient'),
        ),
        migrations.AlterModelTable(
            name='messages',
            table='messages',
        ),
    ]
