# Generated by Django 5.2 on 2025-08-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_alter_messages_recipient_alter_messages_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='publications_messages'),
        ),
    ]
