# Generated by Django 5.2 on 2025-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notifications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('message_response', 'Сообщение'), ('friend_request', 'Запрос в друзья'), ('friend_response', 'Ответ о дружбе ')]),
        ),
    ]
